blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from post.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('post.urls', namespace='post')),
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django_sitemaps'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import post_list, post_detail, PostListView, post_share, search_view
from .feeds import PostFeed

app_name = 'post'
urlpatterns = [
    path('', post_list, name='post-list'),
    path('tag/<slug:tag_slug>', post_list, name="post-list-by-tag"),
    # path('', PostListView.as_view(), name="post-list"),
    path('post-detail/<int:year>-<int:month>-<int:day>/<slug:post_slug>', post_detail, name='post-detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('feed/', PostFeed(), name='post_feed'),
    path('post-search/', search_view, name='post_search')
]

post/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PostManager(models.Manager):
    def get_queryset(self):
        return super(PostManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    status_choices = [
        ('draft', 'Draft'),
        ('published', 'Published')
    ]
    author = models.ForeignKey(User, on_delete=CASCADE, related_name="blog_posts",
                               related_query_name="blog_posts")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique_for_date="publish", db_index=True, allow_unicode=True)
    text = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=status_choices, default='draft')
    tags = TaggableManager()

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PostManager()

    def get_absolute_url(self):
        return reverse('post:post-detail',
                       args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE, related_name="comments", related_query_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created_at',)

    def __Str__(self):
        return f'Comment by {self.name} on {self.post}'

post/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Comment
messages = {
    'required': 'لطفا فیلد مورد نظر را پر نمایید',
    'invalid': 'لطفا ایمیل صحیح را وارد نمایید',
    'max_length': 'تعداد کاراکتر های ورودی بیشتر از حد مجاز است',
    'min_length': 'تعداد کاراکتر های ورودی کمتر از حد مجاز است'
}


class EmailPostForm(forms.Form):
    name = forms.CharField(label=_("نام"), max_length=25, error_messages=messages)
    email = forms.EmailField(label=_("ایمیل فرستنده"), error_messages=messages)
    to = forms.EmailField(label=_("ایمیل گیرنده"), required=True, error_messages=messages)
    comment = forms.CharField(label=_("متن"), widget=forms.Textarea, required=False)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text')
        labels = {
            "name": _("نام"),
            "email": _("ایمیل"),
            "text": _("متن")
        }


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)

post/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector
from .searching_methods import regular_search, stemming_ranking, weighting, trigram_search


# Create your views here.
def post_list(request, tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)
    page = request.GET.get('page-num')
    pages_range_str = '['
    try:
        posts = paginator.page(page)
        pages_range = paginator.get_elided_page_range(page, on_each_side=1, on_ends=1)
    except PageNotAnInteger:
        posts = paginator.page(1)
        pages_range = paginator.get_elided_page_range(1, on_each_side=1, on_ends=1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        pages_range = paginator.get_elided_page_range(paginator.num_pages, on_each_side=1, on_ends=1)
    for item in pages_range:
        pages_range_str += str(item)
    return render(request, 'blog/posts/list.html', {'posts': posts, 'pages_range': pages_range_str + ']',
                                                    'tag': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    page_kwarg = 'page-num'
    paginate_by = 3
    context_object_name = 'posts'
    template_name = 'blog/posts/list.html'


def post_detail(request, year, month, day, post_slug):
    post = get_object_or_404(Post, slug=post_slug, status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tag=Count('tags')).order_by('-same_tag', '-publish')[:4]
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    return render(request, 'blog/posts/detail.html', {'detail': post, 'comments': comments,
                                                      'comment_form': comment_form, 'new_comment': new_comment,
                                                      'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    form = EmailPostForm()
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['name']} recommends you read {post.title}"
            message = f"read {post.title} at {post_url} \n\n {data['name']} comments: {data['comment']}"
            send_mail(subject, message, "alirezara98@gmail.com", [data['to'], ])
            sent = True
    return render(request, 'blog/posts/share.html', {'post': post, 'form': form, 'sent': sent})


def search_view(request):
    form = SearchForm()
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            obj = Post.published.all()
            # ---regular search---
            result = regular_search(obj, query)
            # ---stemming and ranking search
            # result = stemming_ranking(obj, query)
            # ---weighting query---
            # result = weighting(obj, query)
            # ---search by trigram---
            # result = trigram_search(obj, query)
    return render(request, 'blog/posts/search.html', {'form': form, 'query': query, 'result': result})

templates/base/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/main.css" %}" rel="stylesheet">
        {% block style %}{% endblock %}
    </head>
    <body>
        <div id="header"></div>
        <div id="content" style="text-align: right;">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>بلاگ من</h2>
            <div id="home-btn">
                <a href="{% url "post:post-list" %}">صفحه اصلی</a>
            </div>
            <p> پست به بلاگ اضافه شده است. {% total_posts_tag %}تا کنون </p>
            <a href="{% url 'post:post_feed' %}">subscribe blog feed</a>
            <h2>آخرین پست ها</h2>
            <p>{% show_latest_posts 4 %}</p>
            <h2>پست های با بیشترین نظر</h2>
            {% most_commented_posts 3 as mc_posts %}
            <ul>
                {% for post in mc_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_next %}
            <a href="?page-num={{ page.next_page_number }}">بعد</a>
        {% endif %}
        <span class="current">
           {{ page.number }} از {{ page.paginator.num_pages }}
        </span>
        {% if page.has_previous %}
            <a href="?page-num={{ page.previous_page_number }}">قبل</a>
        {% endif %}
    </span>
</div>

templates/blog/posts/detail.html
{% extends "base/base.html" %}
{% load blog_tags %}
{% load jformat %}
{% block title %}
    {{ detail.title }}
{% endblock %}
{% block content %}
    <h1>{{ detail.title }}</h1>
    <p class="tags">{{ detail.tags.all | join:" | " }}</p>
    <p class="date">منتشر شده {{ detail.publish|jformat:"%A %d %B %Y %H:%M" }} توسط {{ detail.author }}</p>
    <p>{{ detail.text|markdown }}</p>
    <p>
        <a href="{% url "post:post_share" detail.id %}">اشتراک گذاری</a>
    </p>
    <h3>پست های مشابه</h3>
    {% for similar_post in similar_posts %}
        <p><a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }}</a></p>
    {% empty %}
        <p>پست مشابه ای نیست</p>
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} نظر{{ total_comments | fa_plural }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                نظر {{ forloop.counter }} ثبت شده توسط {{ comment.name }}<br>
                {{ comment.created_at }}
            </p>
            {{ comment.text|linebreaks }}
        </div>
    {% empty %}
        <p>هیچ نظری ثبت نشده است</p>
    {% endfor %}
    {% if new_comment %}
        <h2>نظر شما با موفقیت ثبت شد</h2>
    {% else %}
        <form method="post" novalidate class="forms">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="Add comment">
        </form>
    {% endif %}
{% endblock %}

templates/blog/posts/list.html
{% extends "base/base.html" %}
{% load blog_tags %}
{% load jformat %}
{% block title %}
    Post list
{% endblock %}
{% block content %}
    <h1>بلاگ من</h1>
    {% if tag %}
        <h3>{{ tag.name }}پست های با تگ </h3>
    {% endif %}
    {% for post in posts %}
        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
        <p class="tags">
            تگ ها:
            {% for tag in post.tags.all %}
                <a href="{% url "post:post-list-by-tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">منتشر شده {{ post.publish|jformat:"%A %d %B %Y %H:%M" }} توسط {{ post.author }}</p>
        <p>{{ post.text|markdown|truncatewords:30 }}</p>
    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}
{#    {{ pages_range }}#}
{#    {% include "blog/pagination.html" with page=page_obj %}#}
{% endblock %}

templates/blog/posts/search.html
{% extends 'base/base.html' %}
{% load blog_tags %}

{% block title %}صفحه جستجو{% endblock %}
{% block content %}
    {% if query %}
        <h2>پست هایی شامل {{ query }}</h2>
        <h4>
            {% with result.count as search_results %}
                تعداد{{ search_results }} پست {{ search_results|fa_plural }}پیدا شد
            {% endwith %}
        </h4>
        {% for post in result %}
            <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
            <p>{{ post.text|markdown|truncatechars_html:300 }}</p>
        {% empty %}
            <p>پستی پیدا نشد</p>
        {% endfor %}
        <p><a href="{% url "post:post_search" %}">جستجوی دوباره</a></p>
    {% else %}
        <h3>جستجو</h3>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="جستجو">
        </form>
    {% endif %}
{% endblock %}

templates/blog/posts/share.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Share Post {{ post.id }}{% endblock %}
{% block style %}<link href="{% static "css/content.css" %}" rel="stylesheet">{% endblock %}
{% block content %}
    {% if sent %}
        <h1>ایمیل با موفقیت ارسال شد</h1>
        <p>
            {{ post.title }} به ارسال شد {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>اشتراک گذاری {{ post.title }}</h1>
        <form method="post" novalidate class="forms">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                </div>
                <div>{{ field.label_tag }} {{ field }}</div>
            {% endfor %}
            <input type="submit" value="send email">
        </form>
    {% endif %}
{% endblock %}

templates/blog/side_menu/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>